package l2s.gameserver.skills.enums;

/**
 * @author Hl4p3x
 */
public enum SkillTargetType
{
	TARGET_ALLY,
	TARGET_AREA,
	TARGET_AREA_AIM_CORPSE,
	TARGET_AURA,
	TARGET_SERVITOR_AURA,
	TARGET_CHEST,
	TARGET_CLAN,
	TARGET_CLAN_ONE,
	TARGET_CLAN_ONLY,
	TARGET_CORPSE,
	TARGET_CORPSE_PLAYER,
	TARGET_ENEMY_PET,
	TARGET_ENEMY_SUMMON,
	TARGET_ENEMY_SERVITOR,
	TARGET_FLAGPOLE,
	TARGET_COMMCHANNEL,
	TARGET_HOLY,
	TARGET_ITEM,
	TARGET_NONE,
	TARGET_ONE,
	TARGET_OWNER,
	TARGET_PARTY,
	TARGET_PARTY_WITHOUT_ME,
	TARGET_PARTY_ONE,
	TARGET_PARTY_ONE_WITHOUT_ME,
	TARGET_SERVITORS,
	TARGET_SUMMON,
	TARGET_PET,
	TARGET_ONE_SERVITOR,
	TARGET_ONE_SERVITOR_NO_TARGET,
	TARGET_SELF_AND_SUMMON,
	TARGET_SELF,
	TARGET_SIEGE,
	TARGET_UNLOCKABLE,
	TARGET_GROUND,
	TARGET_SHOOTING,
	// PTS target types
	TARGET_FAN,
	TARGET_FAN_PB,
	TARGET_SQUARE,
	TARGET_SQUARE_PB,
	TARGET_RANGE,
	TARGET_RING_RANGE
}
