package l2s.gameserver.skills.enums;

/**
 * @author Hl4p3x
 */
public enum SkillMagicType
{
	PHYSIC, // Offlike: 0
	MAGIC, // Offlike: 1
	SPECIAL, // Offlike: 2
	MUSIC, // Offlike: 3
	ITEM, // Offlike: 4
	UNK_MAG_TYPE_21, // Offlike: 21
	AWAKED_BUFF, // Offlike: 22
	UNK_MAG_TYPE_23,
	UNK_MAG_TYPE_24,
	UNK_MAG_TYPE_25,
	UNK_MAG_TYPE_26,
	UNK_MAG_TYPE_27,
	UNK_MAG_TYPE_28,
	UNK_MAG_TYPE_29,
	UNK_MAG_TYPE_30,
	UNK_MAG_TYPE_31,
	UNK_MAG_TYPE_32,
	UNK_MAG_TYPE_33,
	UNK_MAG_TYPE_34,
	UNK_MAG_TYPE_35,
	UNK_MAG_TYPE_36,
	UNK_MAG_TYPE_37,
	UNK_MAG_TYPE_38,
	UNK_MAG_TYPE_39,
	UNK_MAG_TYPE_40,
	UNK_MAG_TYPE_41,
	UNK_MAG_TYPE_42,
	UNK_MAG_TYPE_43,
	UNK_MAG_TYPE_44,
	UNK_MAG_TYPE_45,
	UNK_MAG_TYPE_46,
	UNK_MAG_TYPE_47,
	UNK_MAG_TYPE_48,
	UNK_MAG_TYPE_49,
	UNK_MAG_TYPE_50,
	UNK_MAG_TYPE_51,
	UNK_MAG_TYPE_52;
}
